remote_theme: pmarsceill/just-the-docs
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 6
  preview_words_before: 5
  preview_words_after: 5
  rel_url: true
  button: false