remote_theme: pmarsceill/just-the-docs
color_scheme: light
search_enabled: true
search:
  heading_level: 3
  previews: 5
  preview_words_before: 3
  preview_words_after: 5
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false